export { default as ArrowUpIcon } from './arrow_up.svg'
export { default as CloseIcon } from './close.svg'
export { default as LogoIcon } from './logo.svg'
export { default as LogoUaIcon } from './logo_ua.svg'
export { default as UserIcon } from './user.svg'
export { default as ClockIcon } from './clock.svg'
export { default as EyeIcon } from './eye.svg'
